"use client";

import "~/styles/globals.css";
import { type Metadata } from "next";
import Link from "next/link";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { useRouter } from "next/navigation";

// 1. Import your CSS module
import styles from "~/styles/Navbar.module.css";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const Navbar = () => {
  const router = useRouter();

  return (
    // 2. Use your .navbar class
    <nav className={styles.navbar}>
      {/* Logo/Brand */}
      <div className={styles["navbar-logo"]}>
        <h2>
          <Link href="/" style={{ textDecoration: "none", color: "inherit" }}>
            NORA
          </Link>
        </h2>
      </div>

      {/* 3. Use a <ul> with the .navbar-links */}
      <ul className={styles["navbar-links"]}>
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/about">About us</Link>
        </li>

        <li>
          <Link href="/services">Services</Link>
        </li>

        {/* SignIn and UserButton */}
        <li>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </li>
      </ul>
    </nav>
  );
};
